### ISSUE TITLE
CHANGELOG.md

### ISSUE THREAD

**Issue by EddSuarez** [bixlabs/documentation#8]
Include a guideline for changelog in our projects/modules, I found this one [keepchangelog](http://keepachangelog.com/en/0.3.0/).

**Comment by jac1013** [comment]
Hey @EddSuarez I loved that, let's discuss about how we want our ``CHANGELOG`` to look like and after we end with something meaningful I'll make sure to add it to the template project (I'm creating the issue there as well).

It would be good if you can put like a _base_ so we can start discussing on things that we like or not, can you please? Let me know, otherwise I will later.

Thanks!

**Comment by EddSuarez** [comment]
sure, @jac1013. I'll do a PR to include the example shown in http://keepachangelog.com/  so everyone will be able to put comments on that.
